### ISSUE TITLE
Repack problem

### ISSUE THREAD

**Issue by imKota** [ruffnext/DataPack5_Unpacker#1]
Hello!

**Comment by ruffnext** [comment]
I have no windows PC right now, and all my win32 cracks are lost.  It is impossible to fix this problem right now. So I am sorry that I can't help.

There might be some useful tools for you --> https://github.com/regomne/chinesize

Also, you may try to repack it yourself, the python code has described most of the unpack/pack procedure well.

It will be helpful to make a pull request :-)
